const gm = require("gm");
const axios = require("../services/rateLimitedAxios");
const fs = require("fs");
const logger = require('../services/logger.js');

function jpgNameFromUrl(url) {
  const name = url.split('/').pop().split('#')[0].split('?')[0];
  return name.endsWith('.jpg') ? name : `${name}.jpg`;
}

const path = require('path');

async function getBuffer(url) {
  const name = makeImageName(url);
  if (!url) {
    return null;
  }

  const dir = path.join(__dirname, '../temp/scan');
  const filePath = path.join(dir, name);

  if (fs.existsSync(filePath)) {
    buffer = fs.readFileSync(filePath);
  } else {
    buffer = await getImageBuffer(url);
    fs.writeFileSync(filePath, buffer);
  }

  return buffer;
}

function makeImageName(url) {
  const name = jpgNameFromUrl(url)

  const domain = url.split('/')[2] ? url.split('/')[2] : 'unknown'

  return `${domain}_${name}`
}

const cannabinoidSpellingMap = {
  '?R-HHC': '9R-HHC',
  '∆ 9-THC': '∆-9-THC',
  '∆ 9-THCA': '∆-9-THCA',
  '∆ 9-THCVA': 'THCVA',
  '∆-8-THC': '∆-8-THC',
  '∆-9 THC': '∆-9-THC',
  '∆-9 THCA': '∆-9-THCA',
  '∆-9-THC': '∆-9-THC',
  '∆-9-THCA': '∆-9-THCA',
  '∆-9-THCV': 'THCV',
  '∆-9-THCVA': 'THCVA',

  '∆9-THC': '∆-9-THC',
  '∆9-THCA': '∆-9-THCA',
  '∆9-THCVA': 'THCVA',
  '∆8-THC': '∆-8-THC',
  '∆9-THC': '∆-9-THC',
  '∆9-THCA': '∆-9-THCA',
  '∆9-THC': '∆-9-THC',
  '∆9-THCA': '∆-9-THCA',
  '∆9-THCV': 'THCV',

  '∆9 THC': '∆-9-THC',
  '∆9 THCA': '∆-9-THCA',
  '∆9 THCVA': 'THCVA',
  '∆8 THC': '∆-8-THC',
  '∆9 THC': '∆-9-THC',
  '∆9 THCA': '∆-9-THCA',
  '∆9 THC': '∆-9-THC',
  '∆9 THCA': '∆-9-THCA',
  '∆9 THCV': 'THCV',
  '∆9-THCVA': 'THCVA',
  '$-A-10-Tetrahydrocannabinol': 'S-∆-10-THC',
  '4-8-Tetrahydrocannabinol': '∆-8-THC',
  '4-9-Tetrahydrocannabinol': '∆-9-THC',
  '4-9-Tetrahydrocannabinolic': '∆-9-THCA',
  '4-9-Totratydrocannabivarin': 'THCV',
  '75-Hexatydrocarrabiscl': '9S-HHC',
  '75%-Henatydrocarrabingl': '9S-HHC',
  '9-S-HHC': '9S-HHC',
  '95-Hexabydrocannabinol': '9S-HHC',
  '95-Hexabydrocannabinol': '9S-HHC',
  '95-Hexabydrocannabinol': '9S-HHC',
  '95-Hexahydracannabinal': '9S-HHC',
  '95-Hexahydrocannabinol': '9S-HHC',
  '95-Hexatydrocarrabisol': '9S-HHC',
  '9R-Henahydrocannabinol': '9R-HHC',
  '9R-Henahydrocannabinol': '9R-HHC',
  '9R-Hexahydrocannabinol': '9R-HHC',
  '9R-HHC': '9R-HHC',
  '9S-Hexahydrocannabinol': '9S-HHC',
  '9S-HHC': '9S-HHC',
  '9S-HHC': '9S-HHC',
  '9S-HHC': '9S-HHC',
  'A-8-Tetrahydrocannabinol (A-8 THC)': '∆-8-THC',
  'A-8-Tetrahydrocannabinol': '∆-8-THC',
  'A-8-THC': '∆-8-THC',
  'A-9-Tetrabdrocannabiphorol': 'THCP',
  'A-9-Tetrabrydrocannabiphorol': 'THCP',
  'A-9-Tetrabrydrocannabivarini': 'THCP',
  'A-9-Tetrabrydrocannabivarinic': 'THCP',
  'A-9-Tetrabydrocannabighorol': '∆-9-THCO',
  'A-9-Tetrabydrocannabinol': '∆-9-THC',
  'A-9-Tetrabydrocannabiphorol': 'THCP',
  'A-9-Tetrabydrocannabivarinic': 'THCVA',
  'A-9-Tetrahydrocannabino!': '∆-9-THC',
  'A-9-Tetrahydrocannabinol (A-9 THC)': '∆-9-THC',
  'A-9-Tetrahydrocannabinol Acetate (A-9-THCO)': '∆-9-THCO',
  'A-9-Tetrahydrocannabinol': '∆-9-THC',
  'A-9-Tetrahydrocannabinol': '∆-9-THC',
  'A-9-Tetrahydrocannabinolic Acid (THCA-A)': '∆-9-THCA',
  'A-9-Tetrahydrocannabinolic Acid': '∆-9-THCA',
  'A-9-Tetrahydrocannabinolic': '∆-9-THCA',
  'A-9-Tetrahydrocannabiphorel': 'THCP',
  'A-9-Tetrahydrocannabiphorol (A-9-THCP)': 'THCP',
  'A-9-Tetrahydrocannabiphorol': 'THCP',
  'A-9-Tetrahydrocannabivarin (A-9-THCV)': 'THCV',
  'A-9-Tetrahydrocannabivarin': 'THCV',
  'A-9-Tetrahydrocannabivarinic Acid (A-9-THCVA)': 'THCVA',
  'A-9-Tetrahydrocannabivarinic': 'THCVA',
  'A-9-Tetrahydrocannatinolic': '∆-9-THCO',
  'A-9-Tetrahydrocannatinolic': '∆-9-THCO',
  'A-9-Tetratrydrocannabivarinic': 'THCVA',
  'A-9-Tetratydrocannabiphorol': 'THCP',
  'A-9-Tetratydrocannabiphorol': 'THCP',
  'A-9-THC': '∆-9-THC',
  'A-9-THCA-A': '∆-9-THCA',
  'A-9-THCA': '∆-9-THCA',
  'A-9-THCP': 'THCP',
  'A-9-THCV': 'THCV',
  'A-9-THCVA': 'THCVA',
  'A?-THCV': 'THCV',
  'A8-THC': '∆-8-THC',
  'A9-Tetrabydrecamasinalic Ackd (THCA-R)': 'THCA-R',
  'A9-THC': '∆-9-THC',
  'A9-THCA-A': '∆-9-THCA',
  'A9-THCA': '∆-9-THCA',
  'A9-THCV': 'THCV',
  'A9-THCVA': 'THCVA',
  'A9-THCVA': 'THCVA',
  'B cBGA': 'CBGA',
  'B THCA*': '∆-9-THCA',
  'B-9-Tetrabwdrocannabighorol': '∆-9-THCO',
  'Camnabichromenic': 'CBCA',
  'Cannabichearinic': 'CBCA',
  'Cannabichonvene': 'CBC',
  'Cannabichromene': 'CBC',
  'Cannabichromenic': 'CBCA',
  'Cannabicyclol (CBL)': 'CBL',
  'Cannabidiol (CBD)': 'CBD',
  'Cannabidiolic Acid': 'CBDA',
  'Cannabidivaria': 'CBDV',
  'Cannabidivarieic': 'CBDVA',
  'Cannabidivarin (CBDV)': 'CBDV',
  'Cannabidivarinic Acid (CBDVA)': 'CBDVA',
  'Cannabidivarinic Acid': 'THCV',
  'Cannabigeral': 'CBG',
  'Cannabigerdl': 'CBG',
  'Cannabigerol (CBG)': 'CBG',
  'cannabigerol': 'CBG',
  'Cannabigerolic Acid': 'CBGA',
  'Cannabigerolic': 'CBGA',
  'Cannabinol (CBN)': 'CBN',
  'Cannabinol': 'CBN',
  'Cannabinolic': 'CBNA',
  'Cannabinolic Acid (CBNA)': 'CBNA',
  'Cannabldiolic': 'CBDA',
  'Cannablgerolic': 'CBG',
  'Cannatichromene': 'CBC',
  'Cannatidiolic': 'CBD',
  'Cannatigerol': 'CBG',
  'Cannatinol': 'CBN',
  'Cannubichromene': 'CBC',
  'Cannubidiol': 'CBD',
  'Cannubidivarinic': 'CBDVA',
  'Cannubidivarinne': 'CBDVA',
  'Canrabidiolic': 'CBDA',
  'Canrabidivarin': 'CBDVA',
  'Canrabinolic': 'CBN',
  'Canrubidivarieic': 'CBDVA',
  'Canrudschromenic': 'CBC',
  'Canrudsdial': 'CBD',
  'Carnabigerol': 'CBG',
  'Carrubichromenic': 'CBC',
  'Carrubirolic': 'CBG',
  'Carrubsrolic': 'CBG',
  'Carrubyrolic': 'CBG',
  'CBC': 'CBC',
  'CBCA': 'CBCA',
  'CBCV': 'CBCV',
  'CBD': 'CBD',
  'CBD*': 'CBD',
  'CBDA': 'CBDA',
  'CBDA*': 'CBDA',
  'CBDA*®': 'CBDA',
  'CBDV': 'CBDV',
  'CBDVA': 'CBDVA',
  'CBG': 'CBG',
  'CBGA': 'CBGA',
  'CBL': 'CBL',
  'CBLA': 'CBLA',
  'CBN': 'CBN',
  'CBNA': 'CBNA',
  'CBT': 'CBT',
  'd8-THC': '∆-8-THC',
  'd9-THC*': '∆-9-THC',
  'Delta 8-Tetrahydrocannabinol': '∆-8-THC',
  'Delta 9-Tetrahydrocannabinol': '∆-9-THC',
  'Delta 9-Tetrahydrocannabinolic': '∆-9-THCA',
  'Delta 9-THCVA': 'THCVA',
  'Delta-9-THC': '∆-9-THC',
  'O-9-Tetrabwdrocannabivarinic': 'THCVA',
  'R-A-10-Tetrahydrocannabinol (R-A-10-THC)': 'R-∆-10-THC',
  'R-A-10-Tetrahydrocannabinol': 'R-∆-10-THC',
  'R-Delta 10-THC': 'R-∆-10-THC',
  'S-A-10-Tetrahydrocannabinol (S-A-10-THC)': 'S-∆-10-THC',
  'S-A-10-Tetrahydrocannabinol': 'S-∆-10-THC',
  'S-Delta 10-THC': 'S-∆-10-THC',
  'Tetrahydrocannabivarin': 'THCV',
  'Tetrahydrocannabivarinic Acid': 'THCVA',
  'Tetrahydrocannabivarinic': 'THCVA',
  'Tetralwdrocannabinol': '∆-9-THC',
  'Tetratwarocamanng': '∆-9-THC',
  'THC': '∆-9-THC',
  'THCA': '∆-9-THCA',
  'THCA*': '∆-9-THCA',
  'THCA*®': '∆-9-THCA',
  'THCO': '∆-9-THCO',
  'THCP': 'THCP',
  'THCV': 'THCV',
  'THCV': 'THCV',
  'THCVa': 'THCVA',
  'THCVA': 'THCVA'
}

const cannabinoidNameList = Array.from(Object.values(cannabinoidSpellingMap)).filter((item, index, self) => self.indexOf(item) === index);

const terpeneSpellingMap = {
  '-Bisabolol': 'Bisabolol',
  '«-Bisabolol': 'Bisabolol',
  '«-Pinene': 'Pinene',
  '1,8-Cineole': 'Eucalyptol',
  '1.8-Cinecle': 'Eucalyptol',
  'a-Bisabolol': 'Bisabolol',
  'a-Bsabolol': 'Bisabolol',
  'a-Finene': 'Pinene',
  'a-Humulene': 'Humulene',
  'a-Pinene': 'Pinene',
  'a-Pinene': 'Pinene',
  'a-Pinens': 'Pinene',
  'a-Terpinene': 'Terpinene',
  'B-Caryophyliene': 'Caryophyllene',
  'B-Caryophyllene': 'Caryophyllene',
  'B-Myrcene': 'Myrcene',
  'Bisabolol': 'Bisabolol',
  'Bormwol': 'Borneol',
  'Bornel': 'Borneol',
  'Borneol': 'Borneol',
  'Borreol': 'Borneol',
  'Borrmeol': 'Borneol',
  'Bsabolol': 'Bisabolol',
  'Camphene': 'Camphene',
  'Carene': 'Carene',
  'Caryophyliene': 'Caryophyllene',
  'CaryophylleneOxide': 'Caryophyllene Oxide',
  'Cinecle': 'Eucalyptol',
  'Cineole': 'Eucalyptol',
  'Citral': 'Citral',
  'Dihydrocarveol': 'Dihydrocarveol',
  'Fenchone': 'Fenchone',
  'Ferxhone': 'Fenchone',
  'Finene': 'Pinene',
  'Humulene': 'Humulene',
  'Limonene': 'Limonene',
  'Limonenes': 'Limonene',
  'Linalool': 'Linalool',
  'Menthol': 'Menthol',
  'Myrcene': 'Myrcene',
  'Nerolidol': 'Nerolidol',
  'o-Humulene': 'Humulene',
  'Ocimene': 'Ocimene',
  'Pinene': 'Pinene',
  'Pulegone': 'Pulegone',
  'Terpinolene': 'Terpinolene',
  'y-Terpinene': 'Terpinolene',
  'α-Bisabolol': 'Bisabolol',
  'α-Humulene': 'Humulene',
  'α-Pinene': 'Pinene',
  'α-Terpinene': 'Terpinene',
  'β-Caryophyllene': 'Caryophyllene',
  'β-Myrcene': 'Myrcene',
  'γ-Terpinene': 'Terpinolene',
};

const terpeneNameList = Array.from(Object.values(terpeneSpellingMap)).filter((item, index, self) => self.indexOf(item) === index);


module.exports = {
  getBuffer,
  cannabinoidNameList,
  terpeneNameList,
  cannabinoidNameList,
  terpeneNameList,
  cannabinoidSpellingMap,
  terpeneSpellingMap
}